# Laboratorium 4 — Pandas: eksploracja danych

**Biblioteki:** `pandas`, `seaborn`, `nycflights13`

---
## Zadanie 2.1 [MG, AC, MB]

Wczytaj ramkę danych `tips` korzystając z polecenia:

```python
import seaborn as sns
tips = sns.load_dataset('tips')
```

a następnie wykonaj poniższe polecenia:

- **(a)** Odczytaj liczbę wierszy i kolumn ramki danych (atrybut `shape`).
- **(b)** Odczytaj typy poszczególnych kolumn ramki danych (atrybut `dtypes`).
- **(c)** Wywołaj metody `describe()` oraz `info()`.
- **(d)** Wywołaj metody `head()`, `tail()`.
- **(e)** Odczytaj nazwy kolumn `ramka_danych.columns`.
- **(f)** Wybierz z ramki danych `tips` wszystkie kolumny między `"tip"` i `"day"` (włącznie),
  nie odwołując się do pozycji tych zmiennych (rozwiązanie powinno zadziałać także
  w przypadku gdy dokonamy losowej permutacji kolumn ramki danych).
- **(g)** Wybierz z ramki danych `tips` co drugą kolumnę.
- **(h)** Wybierz z ramki danych `tips` wiersze odpowiadające kobietom, które zapłaciły
  rachunek w wysokości (20, 30].
- **(i)** Oblicz jaką frakcję rachunku stanowi napiwek.
- **(j)** Wybierz z ramki danych `tips` wiersze odpowiadające sobotom lub niedzielom,
  dla których wysokość napiwku wynosiła co najmniej 30% całego rachunku.

In [1]:
import seaborn as sns
import pandas as pd
import numpy as np

tips = sns.load_dataset('tips')
tips.head(3)

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3

### (a) Liczba wierszy i kolumn — `shape`

In [2]:
print(f"Liczba wierszy : {tips.shape[0]}")
print(f"Liczba kolumn  : {tips.shape[1]}")
print(f"shape          : {tips.shape}")

Liczba wierszy : 244
Liczba kolumn  : 7
shape          : (244, 7)

### (b) Typy kolumn — `dtypes`

In [3]:
tips.dtypes

total_bill     float64
tip            float64
sex           category
smoker        category
day           category
time          category
size             int64
dtype: object

### (c) `describe()` i `info()`

In [4]:
tips.describe()

       total_bill         tip        size
count  244.000000  244.000000  244.000000
mean    19.785943    2.998279    2.569672
std      8.902412    1.383638    0.951100
min      3.070000    1.000000    1.000000
25%     13.347500    2.000000    2.000000
50%     17.795000    2.900000    2.000000
75%     24.127500    3.562500    3.000000
max     50.810000   10.000000    6.000000

In [5]:
tips.describe(include='all')

        total_bill         tip   sex smoker  day    time        size
count   244.000000  244.000000   244    244  244     244  244.000000
unique         NaN         NaN     2      2    4       2         NaN
top            NaN         NaN  Male     No  Sat  Dinner         NaN
freq           NaN         NaN   157    151   87     176         NaN
mean     19.785943    2.998279   NaN    NaN  NaN     NaN    2.569672
std       8.902412    1.383638   NaN    NaN  NaN     NaN    0.951100
min       3.070000    1.000000   NaN    NaN  NaN     NaN    1.000000
25%      13.347500    2.000000   NaN    NaN  NaN     NaN    2.000000
50%      17.795000    2.900000   NaN    NaN  NaN     NaN    2.000000
75%      24.127500    3.562500   NaN    NaN  NaN     NaN    3.000000
max      50.810000   10.000000   NaN    NaN  NaN     NaN    6.000000

In [6]:
tips.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 244 entries, 0 to 243
Data columns (total 7 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   total_bill  244 non-null    float64
 1   tip         244 non-null    float64
 2   sex         244 non-null    category
 3   smoker      244 non-null    category
 4   day         244 non-null    category
 5   time        244 non-null    category
 6   size        244 non-null    int64
dtypes: category(4), float64(2), int64(1)
memory usage: 7.4 KB

### (d) `head()` i `tail()`

In [7]:
tips.head()

   total_bill   tip     sex smoker  day    time  size
0       16.99  1.01  Female     No  Sun  Dinner     2
1       10.34  1.66    Male     No  Sun  Dinner     3
2       21.01  3.50    Male     No  Sun  Dinner     3
3       23.68  3.31    Male     No  Sun  Dinner     2
4       24.59  3.61  Female     No  Sun  Dinner     4

In [8]:
tips.tail()

     total_bill   tip     sex smoker   day    time  size
239       29.03  5.92    Male     No   Sat  Dinner     3
240       27.18  2.00  Female    Yes   Sat  Dinner     2
241       22.67  2.00    Male    Yes   Sat  Dinner     2
242       17.82  1.75    Male     No   Sat  Dinner     2
243       18.78  3.00  Female     No  Thur  Dinner     2

### (e) Nazwy kolumn

In [9]:
tips.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size'], dtype='object')

In [10]:
tips.columns.tolist()

['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size']

### (f) Kolumny między „tip" a „day" (włącznie) — bez pozycji

In [11]:
tips.loc[:, 'tip':'day'].head()

    tip     sex smoker  day
0  1.01  Female     No  Sun
1  1.66    Male     No  Sun
2  3.50    Male     No  Sun
3  3.31    Male     No  Sun
4  3.61  Female     No  Sun

In [12]:
tips.loc[:, 'day':'tip'].head()

Empty DataFrame
Columns: []
Index: [0, 1, 2, 3, 4]

Używamy `get_loc()` zamiast `loc[:, 'tip':'day']` jeśli nie wiemy które pole jest pierwsze 'tip', czy 'day', bo to drugie zależy od aktualnej kolejności kolumn.

In [13]:
cols  = tips.columns
left  = min(cols.get_loc('tip'), cols.get_loc('day'))
right = max(cols.get_loc('tip'), cols.get_loc('day'))

tips_tip_day = tips.iloc[:, left : right + 1]
tips_tip_day.head()

    tip     sex smoker  day
0  1.01  Female     No  Sun
1  1.66    Male     No  Sun
2  3.50    Male     No  Sun
3  3.31    Male     No  Sun
4  3.61  Female     No  Sun

### (g) Co druga kolumna

In [14]:
tips.iloc[:, ::2].head()

   total_bill     sex  day  size
0       16.99  Female  Sun     2
1       10.34    Male  Sun     3
2       21.01    Male  Sun     3
3       23.68    Male  Sun     2
4       24.59  Female  Sun     4

### (h) Kobiety z rachunkiem w przedziale (20, 30]

In [15]:
mask_f    = tips['sex'] == 'Female'
mask_bill = tips['total_bill'].between(20, 30, inclusive='right')

result_h = tips.loc[mask_f & mask_bill]
print(f"Liczba pasujących wierszy: {len(result_h)}")
result_h

Liczba pasujących wierszy: 20

     total_bill   tip     sex smoker   day    time  size
4         24.59  3.61  Female     No   Sun  Dinner     4
21        20.29  2.75  Female     No   Sat  Dinner     2
33        20.69  2.45  Female     No   Sat  Dinner     4
57        26.41  1.50  Female     No   Sat  Dinner     2
72        26.86  3.14  Female    Yes   Sat  Dinner     2
73        25.28  5.00  Female    Yes   Sat  Dinner     2
94        22.75  3.25  Female     No   Fri  Dinner     2
103       22.42  3.48  Female    Yes   Sat  Dinner     2
104       20.92  4.08  Female     No   Sat  Dinner     2
114       25.71  4.00  Female     No   Sun  Dinner     3
119       24.08  2.92  Female     No  Thur   Lunch     4
125       29.80  4.20  Female     No  Thur   Lunch     6
131       20.27  2.83  Female     No  Thur   Lunch     2
143       27.05  5.00  Female     No  Thur   Lunch     6
155       29.85  5.14  Female     No   Sun  Dinner     5
157       25.00  3.75  Female     No   Sun  Dinner     4
186       20.90  3.50  Female    Yes   Sun  Dinner     3
214       28.17  6.50  Female    Yes   Sat  Dinner     3
229       22.12  2.88  Female    Yes   Sat  Dinner     2
240       27.18  2.00  Female    Yes   Sat  Dinner     2

### (i) Frakcja napiwku

$$\text{tip\_fraction} = \dfrac{\text{tip}}{\text{total\_bill}}$$

In [16]:
tips['tip_fraction'] = tips['tip'] / tips['total_bill']
tips[['total_bill', 'tip', 'tip_fraction']].head(10)

   total_bill   tip  tip_fraction
0       16.99  1.01      0.059447
1       10.34  1.66      0.160542
2       21.01  3.50      0.166587
3       23.68  3.31      0.139780
4       24.59  3.61      0.146808
5       25.29  4.71      0.186240
6        8.77  2.00      0.228050
7       26.88  3.12      0.116071
8       15.04  1.96      0.130319
9       14.78  3.23      0.218539

### (j) Sobota lub niedziela z napiwkiem ≥ 30%

In [17]:
mask_weekend = tips['day'].isin(['Sat', 'Sun'])
mask_30      = tips['tip_fraction'] >= 0.30

result_j = tips.loc[mask_weekend & mask_30]
print(f"Liczba pasujących wierszy: {len(result_j)}")
result_j[['total_bill', 'tip', 'tip_fraction', 'day', 'sex']] \
    .sort_values('tip_fraction', ascending=False)

Liczba pasujących wierszy: 3

     total_bill   tip  tip_fraction  day     sex
172        7.25  5.15      0.710345  Sun    Male
178        9.60  4.00      0.416667  Sun  Female
67         3.07  1.00      0.325733  Sat  Female

---
## Zadanie 2.2

Wczytaj ramkę danych `tips` korzystając z polecenia:

```python
import seaborn as sns
tips = sns.load_dataset('tips')
```

a następnie odpowiedz na poniższe pytania:

- **(a)** Czy na podstawie danych możemy stwierdzić, że kobiety udzielają wyższych napiwków?
- **(b)** Czy na podstawie danych możemy stwierdzić, że wysokość rachunku opłacanego przez
  palących mężczyzn zależy od dnia, w którym odwiedzili restaurację?

### (a) Czy kobiety udzielają wyższych napiwków?

In [18]:
# Upewniamy się, że kolumna tip_fraction istnieje
if 'tip_fraction' not in tips.columns:
    tips['tip_fraction'] = tips['tip'] / tips['total_bill']

# Porównanie napiwków (wartość bezwzględna i frakcja) wg płci
summary_sex = tips.groupby('sex')[['tip', 'tip_fraction']].agg(['mean', 'median'])
print(summary_sex)

             tip        tip_fraction
            mean median         mean    median
sex
Male    3.089618   3.00     0.157651  0.153492
Female  2.833448   2.75     0.166491  0.155581

C:\Users\malys\AppData\Local\Temp\ipykernel_22616\2959981593.py:6: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  summary_sex = tips.groupby('sex')[['tip', 'tip_fraction']].agg(['mean', 'median'])

In [19]:
# Rozkłady napiwków wg płci
tips.groupby('sex')['tip'].describe()

C:\Users\malys\AppData\Local\Temp\ipykernel_22616\49244671.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips.groupby('sex')['tip'].describe()

        count      mean       std  min  25%   50%   75%   max
sex
Male    157.0  3.089618  1.489102  1.0  2.0  3.00  3.76  10.0
Female   87.0  2.833448  1.159495  1.0  2.0  2.75  3.50   6.5

In [20]:
# Test Manna-Whitneya (nieparametryczny) — H0: rozkłady napiwków są identyczne
from scipy import stats

male_tips   = tips.loc[tips['sex'] == 'Male',   'tip']
female_tips = tips.loc[tips['sex'] == 'Female', 'tip']

stat, p_value = stats.mannwhitneyu(female_tips, male_tips, alternative='two-sided')
print(f"Statystyka U = {stat:.1f},  p-value = {p_value:.4f}")
print()
if p_value < 0.05:
    print("Wynik: różnica istotna statystycznie (α=0.05).")
    if female_tips.median() > male_tips.median():
        print("Kobiety udzielają statystycznie wyższych napiwków (mediana).")
    else:
        print("Mężczyźni udzielają statystycznie wyższych napiwków (mediana).")
else:
    print("Wynik: brak podstaw do odrzucenia H0 — różnica NIE jest istotna statystycznie.")

Statystyka U = 6369.5,  p-value = 0.3834

Wynik: brak podstaw do odrzucenia H0 — różnica NIE jest istotna statystycznie.

### (b) Czy rachunek palących mężczyzn zależy od dnia wizyty?

In [21]:
# Podzbiór: palący mężczyźni
male_smokers = tips.loc[(tips['sex'] == 'Male') & (tips['smoker'] == 'Yes')]
print(f"Liczba obserwacji: {len(male_smokers)}")
male_smokers.groupby('day')['total_bill'].describe()

Liczba obserwacji: 60

C:\Users\malys\AppData\Local\Temp\ipykernel_22616\3589861637.py:4: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  male_smokers.groupby('day')['total_bill'].describe()

      count       mean        std    min      25%     50%      75%    max
day
Thur   10.0  19.171000   6.757421  10.34  15.6100  17.645  20.2575  32.68
Fri     8.0  20.452500  10.943815   8.58  12.1275  17.215  27.7025  40.17
Sat    27.0  21.837778   9.988045   7.74  15.1850  20.290  26.2400  50.81
Sun    15.0  26.141333  10.693824   7.25  17.3550  23.330  33.7650  45.35

In [22]:
# Test Kruskala-Wallisa — H0: rozkłady rachunków są identyczne we wszystkich dniach
groups = [grp['total_bill'].values for _, grp in male_smokers.groupby('day')]

stat_kw, p_kw = stats.kruskal(*groups)
print(f"Statystyka H = {stat_kw:.3f},  p-value = {p_kw:.4f}")
print()
if p_kw < 0.05:
    print("Wynik: różnica istotna statystycznie — wysokość rachunku zależy od dnia wizyty.")
else:
    print("Wynik: brak podstaw do odrzucenia H0 — nie stwierdzono zależności od dnia.")

Statystyka H = 3.692,  p-value = 0.2967

Wynik: brak podstaw do odrzucenia H0 — nie stwierdzono zależności od dnia.

C:\Users\malys\AppData\Local\Temp\ipykernel_22616\293390314.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  groups = [grp['total_bill'].values for _, grp in male_smokers.groupby('day')]

---
## Zadanie 2.4

Będziemy korzystać z bazy danych `nycflights13`, składającej się z następujących ramek danych:

| Ramka | Opis |
|---|---|
| `flights` | Informacje o lotach z NYC (EWR, JFK, LGA) w 2013 r. |
| `airports` | Nazwy i lokalizacje lotnisk |
| `planes` | Dane techniczne samolotów |
| `airlines` | Tłumaczenie kodów przewoźników na nazwy |
| `weather` | Godzinowe dane meteorologiczne dla każdego lotniska |

Zapoznaj się z ramkami danych:

- wykorzystaj metodę `.info()` i `.describe()`,
- poznaj wymiar ramek danych np. `shape`,
- wypisz kilka pierwszych i ostatnich wierszy ramek danych `.head()`, `.tail()`.

In [23]:
# pip install nycflights13

In [24]:
import nycflights13

In [25]:
from nycflights13 import flights, airports, planes, airlines, weather

datasets = {
    'flights'  : flights,
    'airports' : airports,
    'planes'   : planes,
    'airlines' : airlines,
    'weather'  : weather,
}

for name, df in datasets.items():
    print(f"{'='*55}")
    print(f"  {name.upper()}  —  shape: {df.shape}")
    print(f"{'='*55}")
    df.info()
    print()

=======================================================
  FLIGHTS  —  shape: (336776, 19)
=======================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 336776 entries, 0 to 336775
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   year            336776 non-null  int64
 1   month           336776 non-null  int64
 2   day             336776 non-null  int64
 3   dep_time        328521 non-null  float64
 4   sched_dep_time  336776 non-null  int64
 5   dep_delay       328521 non-null  float64
 6   arr_time        328063 non-null  float64
 7   sched_arr_time  336776 non-null  int64
 8   arr_delay       327346 non-null  float64
 9   carrier         336776 non-null  object
 10  flight          336776 non-null  int64
 11  tailnum         334264 non-null  object
 12  origin          336776 non-null  object
 13  dest            336776 non-null  object
 14  air_time        327346 non-null  float64
 15  distance        336776 non-null  int64
 16  hour            336776 non-null  int64
 17  minute          336776 non-null  int64
 18  time_hour       336776 non-null  object
dtypes: float64(5), int64(9), object(5)
memory usage: 48.8+ MB

=======================================================
  AIRPORTS  —  shape: (1458, 8)
=======================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1458 entries, 0 to 1457
Data columns (total 8 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   faa     1458 non-null   object
 1   name    1458 non-null   object
 2   lat     1458 non-null   float64
 3   lon     1458 non-null   float64
 4   alt     1458 non-null   int64
 5   tz      1458 non-null   int64
 6   dst     1458 non-null   object
 7   tzone   1455 non-null   object
dtypes: float64(2), int64(2), object(4)
memory usage: 91.3+ KB

=======================================================
  PLANES  —  shape: (3322, 9)
=======================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3322 entries, 0 to 3321
Data columns (total 9 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   tailnum       3322 non-null   object
 1   year          3252 non-null   float64
 2   type          3322 non-null   object
 3   manufacturer  3322 non-null   object
 4   model         3322 non-null   object
 5   engines       3322 non-null   int64
 6   seats         3322 non-null   int64
 7   speed         23 non-null     float64
 8   engine        3322 non-null   object
dtypes: float64(2), int64(2), object(5)
memory usage: 233.7+ KB

=======================================================
  AIRLINES  —  shape: (16, 2)
=======================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 16 entries, 0 to 15
Data columns (total 2 columns):
 #   Column   Non-Null Count  Dtype
---  ------   --------------  -----
 0   carrier  16 non-null     object
 1   name     16 non-null     object
dtypes: object(2)
memory usage: 388.0+ bytes

=======================================================
  WEATHER  —  shape: (26115, 15)
=======================================================
<class 'pandas.core.frame.DataFrame'>
RangeIndex: 26115 entries, 0 to 26114
Data columns (total 15 columns):
 #   Column      Non-Null Count  Dtype
---  ------      --------------  -----
 0   origin      26115 non-null  object
 1   year        26115 non-null  int64
 2   month       26115 non-null  int64
 3   day         26115 non-null  int64
 4   hour        26115 non-null  int64
 5   temp        26114 non-null  float64
 6   dewp        26114 non-null  float64
 7   humid       26114 non-null  float64
 8   wind_dir    25655 non-null  float64
 9   wind_speed  26111 non-null  float64
 10  wind_gust   5337 non-null   float64
 11  precip      26115 non-null  float64
 12  pressure    23386 non-null  float64
 13  visib       26115 non-null  float64
 14  time_hour   26115 non-null  object
dtypes: float64(9), int64(4), object(2)
memory usage: 3.0+ MB

In [26]:
# describe() dla każdej ramki
for name, df in datasets.items():
    print(f"\n{'─'*50}\n  {name.upper()} — describe()\n{'─'*50}")
    display(df.describe(include='all'))

──────────────────────────────────────────────────
  FLIGHTS — describe()
──────────────────────────────────────────────────

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
count,336776.0,336776.000000,336776.000000,328521.000000,336776.000000,328521.000000,328063.000000,336776.000000,327346.000000,336776,336776.000000,334264,336776,336776,327346.000000,336776.000000,336776.000000,336776.000000,336776
unique,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,16,NaN,4043,3,105,NaN,NaN,NaN,NaN,6936
top,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,UA,NaN,N725MQ,EWR,ORD,NaN,NaN,NaN,NaN,2013-09-13T12:00:00Z
freq,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,58665,NaN,575,120835,17283,NaN,NaN,NaN,NaN,94
mean,2013.0,6.548510,15.710787,1349.109947,1344.254840,12.639070,1502.054999,1536.380220,6.895377,NaN,1971.923620,NaN,NaN,NaN,150.686460,1039.912604,13.180247,26.230100,NaN
std,0.0,3.414457,8.768607,488.281791,467.335756,40.210061,533.264132,497.457142,44.633292,NaN,1632.471938,NaN,NaN,NaN,93.688305,733.233033,4.661316,19.300846,NaN
min,2013.0,1.000000,1.000000,1.000000,106.000000,-43.000000,1.000000,1.000000,-86.000000,NaN,1.000000,NaN,NaN,NaN,20.000000,17.000000,1.000000,0.000000,NaN
25%,2013.0,4.000000,8.000000,907.000000,906.000000,-5.000000,1104.000000,1124.000000,-17.000000,NaN,553.000000,NaN,NaN,NaN,82.000000,502.000000,9.000000,8.000000,NaN
50%,2013.0,7.000000,16.000000,1401.000000,1359.000000,-2.000000,1535.000000,1556.000000,-5.000000,NaN,1496.000000,NaN,NaN,NaN,129.000000,872.000000,13.000000,29.000000,NaN
75%,2013.0,10.000000,23.000000,1744.000000,1729.000000,11.000000,1940.000000,1945.000000,14.000000,NaN,3465.000000,NaN,NaN,NaN,192.000000,1389.000000,17.000000,44.000000,NaN
max,2013.0,12.000000,31.000000,2400.000000,2359.000000,1301.000000,2400.000000,2359.000000,1272.000000,NaN,8500.000000,NaN,NaN,NaN,695.000000,4983.000000,23.000000,59.000000,NaN

──────────────────────────────────────────────────
  AIRPORTS — describe()
──────────────────────────────────────────────────

,faa,name,lat,lon,alt,tz,dst,tzone
count,1458,1458,1458.000000,1458.000000,1458.000000,1458.000000,1458,1455
unique,1458,1440,NaN,NaN,NaN,NaN,3,9
top,04G,Municipal Airport,NaN,NaN,NaN,NaN,A,America/New_York
freq,1,5,NaN,NaN,NaN,NaN,1388,519
mean,NaN,NaN,41.648008,-103.392289,1001.415638,-6.518519,NaN,NaN
std,NaN,NaN,10.449509,29.843118,1523.626105,1.623016,NaN,NaN
min,NaN,NaN,19.721375,-176.646000,-54.000000,-10.000000,NaN,NaN
25%,NaN,NaN,34.257539,-119.185652,70.250000,-8.000000,NaN,NaN
50%,NaN,NaN,40.087722,-94.661854,473.000000,-6.000000,NaN,NaN
75%,NaN,NaN,45.067150,-82.516717,1062.500000,-5.000000,NaN,NaN
max,NaN,NaN,72.270833,174.113620,9078.000000,8.000000,NaN,NaN

──────────────────────────────────────────────────
  PLANES — describe()
──────────────────────────────────────────────────

,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
count,3322,3252.000000,3322,3322,3322,3322.000000,3322.000000,23.000000,3322
unique,3322,NaN,3,35,127,NaN,NaN,NaN,6
top,N10156,NaN,Fixed wing multi engine,BOEING,737-7H4,NaN,NaN,NaN,Turbo-fan
freq,1,NaN,3292,1630,361,NaN,NaN,NaN,2750
mean,NaN,2000.484010,NaN,NaN,NaN,1.995184,154.316376,236.782609,NaN
std,NaN,7.193425,NaN,NaN,NaN,0.117593,73.654974,149.759794,NaN
min,NaN,1956.000000,NaN,NaN,NaN,1.000000,2.000000,90.000000,NaN
25%,NaN,1997.000000,NaN,NaN,NaN,2.000000,140.000000,107.500000,NaN
50%,NaN,2001.000000,NaN,NaN,NaN,2.000000,149.000000,162.000000,NaN
75%,NaN,2005.000000,NaN,NaN,NaN,2.000000,182.000000,432.000000,NaN
max,NaN,2013.000000,NaN,NaN,NaN,4.000000,450.000000,432.000000,NaN

──────────────────────────────────────────────────
  AIRLINES — describe()
──────────────────────────────────────────────────

       carrier               name
count       16                 16
unique      16                 16
top         9E  Endeavor Air Inc.
freq         1                  1

──────────────────────────────────────────────────
  WEATHER — describe()
──────────────────────────────────────────────────

,origin,year,month,day,hour,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
count,26115,26115.0,26115.000000,26115.000000,26115.000000,26114.000000,26114.000000,26114.000000,25655.000000,26111.000000,5337.000000,26115.000000,23386.000000,26115.000000,26115
unique,3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,8714
top,JFK,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,2013-01-01T06:00:00Z
freq,8706,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,3
mean,NaN,2013.0,6.503733,15.675321,11.490791,55.260392,41.439985,62.530059,199.761060,10.517488,25.487071,0.004469,1017.898751,9.255372,NaN
std,NaN,0.0,3.438328,8.762177,6.912423,17.787852,19.386236,19.395918,107.306847,8.539253,5.954958,0.030154,7.423827,2.055052,NaN
min,NaN,2013.0,1.000000,1.000000,0.000000,10.940000,-9.940000,12.740000,0.000000,0.000000,16.110920,0.000000,983.800000,0.000000,NaN
25%,NaN,2013.0,4.000000,8.000000,6.000000,39.920000,26.060000,47.050000,120.000000,6.904680,20.714040,0.000000,1012.900000,10.000000,NaN
50%,NaN,2013.0,7.000000,16.000000,11.000000,55.400000,42.080000,61.790000,220.000000,10.357020,24.166380,0.000000,1017.600000,10.000000,NaN
75%,NaN,2013.0,9.000000,23.000000,17.000000,69.980000,57.920000,78.790000,290.000000,13.809360,28.769500,0.000000,1023.000000,10.000000,NaN
max,NaN,2013.0,12.000000,31.000000,23.000000,100.040000,78.080000,100.000000,360.000000,1048.360580,66.745240,1.210000,1042.100000,10.000000,NaN

In [27]:
# head() i tail() dla każdej ramki
for name, df in datasets.items():
    print(f"\n{'─'*50}\n  {name.upper()} — head(3) / tail(3)\n{'─'*50}")
    display(df.head(3))
    display(df.tail(3))

──────────────────────────────────────────────────
  FLIGHTS — head(3) / tail(3)
──────────────────────────────────────────────────

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
0,2013,1,1,517.0,515,2.0,830.0,819,11.0,UA,1545,N14228,EWR,IAH,227.0,1400,5,15,2013-01-01T10:00:00Z
1,2013,1,1,533.0,529,4.0,850.0,830,20.0,UA,1714,N24211,LGA,IAH,227.0,1416,5,29,2013-01-01T10:00:00Z
2,2013,1,1,542.0,540,2.0,923.0,850,33.0,AA,1141,N619AA,JFK,MIA,160.0,1089,5,40,2013-01-01T10:00:00Z

,year,month,day,dep_time,sched_dep_time,dep_delay,arr_time,sched_arr_time,arr_delay,carrier,flight,tailnum,origin,dest,air_time,distance,hour,minute,time_hour
336773,2013,9,30,NaN,1210,NaN,NaN,1330,NaN,MQ,3461,N535MQ,LGA,BNA,NaN,764,12,10,2013-09-30T16:00:00Z
336774,2013,9,30,NaN,1159,NaN,NaN,1344,NaN,MQ,3572,N511MQ,LGA,CLE,NaN,419,11,59,2013-09-30T15:00:00Z
336775,2013,9,30,NaN,840,NaN,NaN,1020,NaN,MQ,3531,N839MQ,LGA,RDU,NaN,431,8,40,2013-09-30T12:00:00Z

──────────────────────────────────────────────────
  AIRPORTS — head(3) / tail(3)
──────────────────────────────────────────────────

,faa,name,lat,lon,alt,tz,dst,tzone
0,04G,Lansdowne Airport,41.130472,-80.619583,1044,-5,A,America/New_York
1,06A,Moton Field Municipal Airport,32.460572,-85.680028,264,-6,A,America/Chicago
2,06C,Schaumburg Regional,41.989341,-88.101243,801,-6,A,America/Chicago

,faa,name,lat,lon,alt,tz,dst,tzone
1455,ZWI,Wilmington Amtrak Station,39.736667,-75.551667,0,-5,A,America/New_York
1456,ZWU,Washington Union Station,38.897460,-77.006430,76,-5,A,America/New_York
1457,ZYP,Penn Station,40.750500,-73.993500,35,-5,A,America/New_York

──────────────────────────────────────────────────
  PLANES — head(3) / tail(3)
──────────────────────────────────────────────────

,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,N10156,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
1,N102UW,1998.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
2,N103US,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan

,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
3319,N998AT,2002.0,Fixed wing multi engine,BOEING,717-200,2,100,NaN,Turbo-fan
3320,N998DL,1992.0,Fixed wing multi engine,MCDONNELL DOUGLAS CORPORATION,MD-88,2,142,NaN,Turbo-jet
3321,N999DN,1992.0,Fixed wing multi engine,MCDONNELL DOUGLAS CORPORATION,MD-88,2,142,NaN,Turbo-jet

──────────────────────────────────────────────────
  AIRLINES — head(3) / tail(3)
──────────────────────────────────────────────────

  carrier                    name
0      9E       Endeavor Air Inc.
1      AA  American Airlines Inc.
2      AS    Alaska Airlines Inc.

   carrier                    name
13      VX          Virgin America
14      WN  Southwest Airlines Co.
15      YV      Mesa Airlines Inc.

──────────────────────────────────────────────────
  WEATHER — head(3) / tail(3)
──────────────────────────────────────────────────

,origin,year,month,day,hour,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
0,EWR,2013,1,1,1,39.02,26.06,59.37,270.0,10.35702,NaN,0.0,1012.0,10.0,2013-01-01T06:00:00Z
1,EWR,2013,1,1,2,39.02,26.96,61.63,250.0,8.05546,NaN,0.0,1012.3,10.0,2013-01-01T07:00:00Z
2,EWR,2013,1,1,3,39.02,28.04,64.43,240.0,11.50780,NaN,0.0,1012.5,10.0,2013-01-01T08:00:00Z

,origin,year,month,day,hour,temp,dewp,humid,wind_dir,wind_speed,wind_gust,precip,pressure,visib,time_hour
26112,LGA,2013,12,30,16,32.00,15.08,49.19,340.0,14.96014,23.0156,0.0,1019.5,10.0,2013-12-30T21:00:00Z
26113,LGA,2013,12,30,17,30.92,12.92,46.74,320.0,17.26170,NaN,0.0,1019.9,10.0,2013-12-30T22:00:00Z
26114,LGA,2013,12,30,18,28.94,10.94,46.41,330.0,18.41248,NaN,0.0,1020.9,10.0,2013-12-30T23:00:00Z

---
## Zadanie 2.5 [MG]

Korzystamy z ramki `planes` z bazy `nycflights13`.

- **(a)** Wybierz tylko unikatowe typy silników (kolumna `engine`).
- **(b)** Jakie typy samolotów były produkowane przez poszczególnych producentów?
  (kolumny `type`, `manufacturer`) — tylko unikalne kombinacje.
- **(c)** Podaj liczbę wystąpień poszczególnych typów silnika (kolumna `engine`).
- **(d)** Policz ile jest unikatowych par (typ silnika, typ samolotu) w danych.
- **(e)** W którym roku dany producent zaczął produkować samoloty o poszczególnych typach silnika?

In [28]:
planes.head(3)

,tailnum,year,type,manufacturer,model,engines,seats,speed,engine
0,N10156,2004.0,Fixed wing multi engine,EMBRAER,EMB-145XR,2,55,NaN,Turbo-fan
1,N102UW,1998.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan
2,N103US,1999.0,Fixed wing multi engine,AIRBUS INDUSTRIE,A320-214,2,182,NaN,Turbo-fan

### (a) Unikatowe typy silników

In [29]:
unique_engines = planes['engine'].unique()
print(f"Liczba unikalnych typów silników: {len(unique_engines)}")
print(unique_engines)

Liczba unikalnych typów silników: 6
['Turbo-fan' 'Turbo-jet' 'Reciprocating' '4 Cycle' 'Turbo-shaft'
 'Turbo-prop']

### (b) Typy samolotów wg producentów — unikalne kombinacje

In [30]:
type_by_manufacturer = (
    planes[['manufacturer', 'type']]
    .drop_duplicates()
    .sort_values(['manufacturer', 'type'])
    .reset_index(drop=True)
)
print(f"Liczba unikalnych kombinacji: {len(type_by_manufacturer)}")
type_by_manufacturer

Liczba unikalnych kombinacji: 37

                     manufacturer                      type
0                      AGUSTA SPA                Rotorcraft
1                          AIRBUS   Fixed wing multi engine
2                AIRBUS INDUSTRIE   Fixed wing multi engine
3           AMERICAN AIRCRAFT INC  Fixed wing single engine
4              AVIAT AIRCRAFT INC  Fixed wing single engine
5          AVIONS MARCEL DASSAULT   Fixed wing multi engine
6                   BARKER JACK L  Fixed wing single engine
7                           BEECH   Fixed wing multi engine
8                            BELL                Rotorcraft
9                          BOEING   Fixed wing multi engine
10                 BOMBARDIER INC   Fixed wing multi engine
11                       CANADAIR   Fixed wing multi engine
12                   CANADAIR LTD   Fixed wing multi engine
13                         CESSNA   Fixed wing multi engine
14                         CESSNA  Fixed wing single engine
15             CIRRUS DESIGN CORP  Fixed wing single engine
16                    DEHAVILLAND  Fixed wing single engine
17                        DOUGLAS   Fixed wing multi engine
18                        EMBRAER   Fixed wing multi engine
19                 FRIEDEMANN JON  Fixed wing single engine
20           GULFSTREAM AEROSPACE   Fixed wing multi engine
21             HURLEY JAMES LARRY  Fixed wing single engine
22                    JOHN G HESS  Fixed wing single engine
23                   KILDALL GARY  Fixed wing single engine
24                LAMBERT RICHARD  Fixed wing single engine
25                    LEARJET INC   Fixed wing multi engine
26                LEBLANC GLENN T  Fixed wing single engine
27                     MARZ BARRY  Fixed wing single engine
28              MCDONNELL DOUGLAS   Fixed wing multi engine
29  MCDONNELL DOUGLAS AIRCRAFT CO   Fixed wing multi engine
30  MCDONNELL DOUGLAS CORPORATION   Fixed wing multi engine
31                    PAIR MIKE E  Fixed wing single engine
32                          PIPER   Fixed wing multi engine
33                          PIPER  Fixed wing single engine
34         ROBINSON HELICOPTER CO                Rotorcraft
35                       SIKORSKY                Rotorcraft
36                   STEWART MACO  Fixed wing single engine

### (c) Liczba wystąpień poszczególnych typów silnika

In [31]:
engine_counts = (
    planes['engine']
    .value_counts()
    .rename_axis('engine')
    .reset_index(name='count')
)
engine_counts

          engine  count
0      Turbo-fan   2750
1      Turbo-jet    535
2  Reciprocating     28
3    Turbo-shaft      5
4        4 Cycle      2
5     Turbo-prop      2

### (d) Liczba unikatowych par (typ silnika, typ samolotu)

In [32]:
n_unique_pairs = planes[['engine', 'type']].drop_duplicates().shape[0]
print(f"Liczba unikatowych par (engine, type): {n_unique_pairs}")
planes[['engine', 'type']].drop_duplicates().sort_values(['engine', 'type'])

Liczba unikatowych par (engine, type): 7

             engine                      type
686         4 Cycle  Fixed wing single engine
427   Reciprocating   Fixed wing multi engine
424   Reciprocating  Fixed wing single engine
0         Turbo-fan   Fixed wing multi engine
51        Turbo-jet   Fixed wing multi engine
1045     Turbo-prop   Fixed wing multi engine
811     Turbo-shaft                Rotorcraft

### (e) Rok, w którym producent zaczął produkować samoloty danego typu silnika

In [33]:
first_year = (
    planes.dropna(subset=['year'])
    .groupby(['manufacturer', 'engine'])['year']
    .min()
    .reset_index()
    .rename(columns={'year': 'first_year'})
    .sort_values(['manufacturer', 'engine'])
    .reset_index(drop=True)
)
first_year

                     manufacturer         engine  first_year
0                      AGUSTA SPA    Turbo-shaft      2001.0
1                          AIRBUS      Turbo-fan      2002.0
2                          AIRBUS      Turbo-jet      2002.0
3                AIRBUS INDUSTRIE      Turbo-fan      1992.0
4                AIRBUS INDUSTRIE      Turbo-jet      1989.0
5              AVIAT AIRCRAFT INC  Reciprocating      2007.0
6          AVIONS MARCEL DASSAULT      Turbo-fan      1986.0
7                           BEECH     Turbo-prop      1967.0
8                            BELL    Turbo-shaft      1975.0
9                          BOEING      Turbo-fan      1965.0
10                         BOEING      Turbo-jet      1984.0
11                 BOMBARDIER INC      Turbo-fan      1998.0
12                       CANADAIR      Turbo-fan      1997.0
13                   CANADAIR LTD      Turbo-jet      1974.0
14                         CESSNA        4 Cycle      1975.0
15                         CESSNA  Reciprocating      1959.0
16                         CESSNA      Turbo-fan      1979.0
17             CIRRUS DESIGN CORP  Reciprocating      2007.0
18                    DEHAVILLAND  Reciprocating      1959.0
19                        DOUGLAS  Reciprocating      1956.0
20                        EMBRAER      Turbo-fan      1998.0
21                        EMBRAER      Turbo-jet      1999.0
22                 FRIEDEMANN JON  Reciprocating      2007.0
23           GULFSTREAM AEROSPACE      Turbo-fan      1992.0
24           GULFSTREAM AEROSPACE      Turbo-jet      1976.0
25                   KILDALL GARY  Reciprocating      1985.0
26                LEBLANC GLENN T  Reciprocating      1985.0
27                     MARZ BARRY  Reciprocating      1993.0
28              MCDONNELL DOUGLAS      Turbo-fan      1986.0
29              MCDONNELL DOUGLAS      Turbo-jet      1975.0
30  MCDONNELL DOUGLAS AIRCRAFT CO      Turbo-fan      1987.0
31  MCDONNELL DOUGLAS CORPORATION      Turbo-jet      1991.0
32                          PIPER  Reciprocating      1968.0
33         ROBINSON HELICOPTER CO    Turbo-shaft      2012.0
34                       SIKORSKY    Turbo-shaft      1985.0
35                   STEWART MACO  Reciprocating      1985.0